import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../(home)/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className="flex h-[100vh] w-[100vw] items-center justify-center">
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
